### ISSUE TITLE
Is there a way to make it work with google script ?

### ISSUE THREAD

**Issue by hutigh** [torikushiii/starrail-auto#1]
Hello ! 

Do you know if we can manage to make it work with [https://script.google.com/](url) ? 
I found one who works with google script but its not as good as yours since it didnt tell me wich reward i got :D

**Comment by torikushiii** [comment]
Hello,

I've never worked with Google Script before but I'll try and see how do they work first!

**Comment by torikushiii** [comment]
Hello,

I've completed your request, you can check it out [here](https://github.com/torikushiii/starrail-auto/tree/master/services/google-script)

Please do tell me if there's anything isn't working properly

**Comment by hutigh** [comment]
Hello ! Wow that was so quick haha ! Thx you so much it seems to work perfectly ! 😊

**Comment by torikushiii** [comment]
That's great to hear, I will close this issue now.

**Comment by hutigh** [comment]
Sorry to réopen it but oopsi it seems it worked when i didnt had any reward to take "You've already checked in today, Trailblazer~" 
But when i had a reward to take i got this error :/
![image](https://github.com/torikushiii/starrail-auto/assets/8125219/b0817a63-2d18-4b1d-b42b-daf330c60182)

I tried with the old script i had in case it was an error from Honkai API but it worked

**Comment by torikushiii** [comment]
That's probably bad on my side since I haven't test it with an account with rewards that haven't been claimed, I'll take a look, thank you for the report!

**Comment by torikushiii** [comment]
Hello,

I've fixed this issue and you can claim the reward normally now. 
![image](https://github.com/torikushiii/starrail-auto/assets/21153445/0fb42533-3f87-47a1-a56f-fccacbab94c6)


You can check it out [here](https://github.com/torikushiii/starrail-auto/blob/master/services/google-script/index.js)

**Comment by hutigh** [comment]
Thx you man i'll try it tomorow !!
