### ISSUE TITLE
Telegram notification for expedition and commands

### ISSUE THREAD

**Issue by JiLleON** [torikushiii/starrail-auto#10]
I noticed that with the values: ```staminaCheck: true```, ```enabled: true```, ```skipCheck: false``` - notifications about completed expeditions are not sent to telegram, but if I change ```skipCheck: true```, then notifications start coming, but this is not exactly what I would like.

Also, telegram commands for manually requesting the status of expeditions/stamina do not work for me. I thought that maybe the problem is in the language of the requested site in cookies, but by changing ```mi18nLang: en-us``` nothing has changed

I can't attach any logs because there aren't any (or I don't know where the output is going). If you have time, then consider running the script in debug mode or something similar so that the user can see for himself what happens in case of errors, as well as provide you with more detailed information. Maybe there is some kind of startup key in nodejs, but I do not know.

Anyway, thanks a lot for your work, your script is very useful even when I run into any problems.

**Comment by torikushiii** [comment]
Hello,

I've fixed the expedition bug where it didn't send any notifications when `skipCheck` set to `false`.

As for the telegram command, it have an interval of 5 seconds before it respond to any command. Have you tried using flags? You can try `node index.js --stamina` or `node index.js --expedition` to see if it's work

**Comment by JiLleON** [comment]
Thanks for the fix, now it sends information about expeditions, but it looks like ```skipCheck: true``` when ```skipCheck: false``` is set (only for expeditions).

The telegram commands didn't work for me because my bot's webhook was busy with another program :D

**Comment by torikushiii** [comment]
What do you mean by "but it looks like `skipCheck: true` when `skipCheck: false` is set (only for expeditions)"?

**Comment by JiLleON** [comment]
![](https://i.imgur.com/fRXE4Xb.png)

**Comment by torikushiii** [comment]
oh you mean the notification is kept being send even if the `skipCheck` set to `false`?

**Comment by JiLleON** [comment]
yes

**Comment by torikushiii** [comment]
I've pushed new commit that fixes this problem and it should send notification properly now

**Comment by JiLleON** [comment]
now it works, thank you!
