### ISSUE TITLE
Errors on Jul 6 commit

### ISSUE THREAD

**Issue by fenchai23** [torikushiii/starrail-auto#13]
Hi! so i decided to update to the latest commits but so far i am trying to run the code but it keeps giving me errors:

```
const id = account.cookie.match(/account_id=(\d+)/)[1];

TypeError: Cannot read properties of null (reading '1')
```
at Account class I think.

all i did was:

- git clone
- npm install
-  properly configure the config.js file
-  node index.js

**Comment by torikushiii** [comment]
Sorry for that small bug, it should be fixed now on the newest commit
