### ISSUE TITLE
Can't run index.js

### ISSUE THREAD

**Issue by FaZe-Goku** [torikushiii/starrail-auto#14]
Got this error:
PS E:\starrail-auto-master> node index.js
file:///E:/starrail-auto-master/config.js:18
        DISCORD_WEBHOOK: discord.com/api/webhooks/1134598997089210368/roB9lo4X-2VQ82ntHBo-SUl-vg9VhBFKwkZwjZO7a3xDF32snCjbePahKIeiMzF2mHTg, // Discord webhook URL
                                                                               ^

SyntaxError: Invalid or unexpected token
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)

Node.js v18.12.1

Sreenshot: 
![image](https://github.com/torikushiii/starrail-auto/assets/77009602/45d42967-875d-443f-9789-182d83500932)

**Comment by torikushiii** [comment]
Did you put double quotes like "https://discordwebhookurl.com"?

And I suggest you to revoke your discord webhook since other people can use that url.
