### ISSUE TITLE
no account_id in cookie

### ISSUE THREAD

**Issue by hazye06** [torikushiii/starrail-auto#15]
I copied the output from the console and pasted it in the cookies property but when I run it shows this

2023-08-12 13:22:19 [WARN]: Account 1 has no account_id in cookie. Skipping fetching account data...

**Comment by torikushiii** [comment]
This is an expected behavior if you didn't provide `account_id=xxxxx` from the full cookie, This will still check you in daily from the hoyolab, but you cannot check for your account stamina an expedition status

**Comment by hazye06** [comment]
where do i get account_id from?
this is what i got from document.cookie in console

![image](https://github.com/torikushiii/starrail-auto/assets/57023139/c79fbc5c-1348-4fbb-8507-1097575633d4)

**Comment by torikushiii** [comment]
It seems they removed it, but you can copy `ltuid=xxxx` and create `account_id=xxxx` and put it at the end of the cookie string, don't forget to put ";" so it should look like this

`ltuid=xxxx; DEVICEFP=xxxxxx; account_id=xxxx`

**Comment by hazye06** [comment]
it worked, but i got a few questions that i would like to ask as well
1. if im using the node.js method i would need to host it right? got any recommendations?
2. what timezone is this based on? and how do i configure it?
![image](https://github.com/torikushiii/starrail-auto/assets/57023139/c552c2ab-372a-47f8-9b53-6102916f9be7)

**Comment by torikushiii** [comment]
1. Yes, you'll need to keep it running if you want to notify you if your stamina almost went full or to do your dailies/weeklies. For recommendation the easiest one would be to use an unused/old laptop or computer to host it, if you didn't have any you can rent a cheap VPS, but maybe between 16-20 this month I'll try to take a look at google script again so you didn't have to install anything and automate it from there.

2. For timezone it's based from your local time.

**Comment by hazye06** [comment]
i managed to host it on free hosting site and got it working.
Heres a final question though
- what are skip checks in terminal

suggestion
- add pings for discord webhook (only ping once, doesnt ping every 30mins and only pings when it first hit the threshold) (diff discord id for diff acc)
- add username for stamina reminder and check-in like dailies reminder

**Comment by torikushiii** [comment]
skip checks means that the script will skip stamina check and expedition check

and for the suggestion, I think I can do that this week
