### ISSUE TITLE
username showed as undefined

### ISSUE THREAD

**Issue by hazye06** [torikushiii/starrail-auto#16]
![image](https://github.com/torikushiii/starrail-auto/assets/57023139/ff61e52a-2cff-40ce-9859-b50e745506ff)
![image](https://github.com/torikushiii/starrail-auto/assets/57023139/1caa8f93-a7e8-49ea-8f9d-98b01b251aba)

**Comment by torikushiii** [comment]
Sorry about that, latest commit should fix it!
