### ISSUE TITLE
[Question] Do the stamina Discord notifications appear only when the command *node index.js* is kept running on my pc?

### ISSUE THREAD

**Issue by FaZe-Goku** [torikushiii/starrail-auto#18]

**Comment by torikushiii** [comment]
yes, due how the timers schedule work you'll need to keep the script running if you want to keep notified. I'm still trying to find a good platform that you can host it yourself without running it on your PC

**Comment by FaZe-Goku** [comment]
> yes, due how the timers schedule work you'll need to keep the script running if you want to keep notified. I'm still trying to find a good platform that you can host it yourself without running it on your PC

I remember a discord bot was able to notify accounts' resin 1-2 years ago
edit: this one https://discordbotlist.com/bots/little-kazuha

**Comment by torikushiii** [comment]
After looking around the bot, it seems that he self-hosted the bot and let people enter their own cookie.

I can build something like that but I'm pretty sure people and me are not gonna be comfortable giving their own cookie to some random bot, at least that what I think.

**Comment by FaZe-Goku** [comment]
> I can build something like that but I'm pretty sure people and me are not gonna be comfortable giving their own cookie to some random bot, at least that what I think.

what can you get from someone' cookie?

**Comment by torikushiii** [comment]
I'm not that fully familiar with how hoyolab authentication works and cookie injection work on that site, but if someone able to grab your cookie they're able to log in into your hoyolab account without inserting `username` and `password` (only your hoyolab account, they still need to input username and password if they're trying to log in to the game)

**Comment by torikushiii** [comment]
I will close this issue since it's inactive, feel free to open this issue again if you have any question/suggestion
