### ISSUE TITLE
Always getting "Command not found" from Telegram, Discord webhook no response

### ISSUE THREAD

**Issue by Malthinae** [torikushiii/starrail-auto#19]
Even after looking at a lot of different parts I have no idea what it could be. Maybe im really dumb and its obvious.
![image](https://github.com/torikushiii/starrail-auto/assets/80122169/cb2807a8-4d9d-4efe-bfb7-f54ad4de6cf7)
![image](https://github.com/torikushiii/starrail-auto/assets/80122169/6fa52d79-4899-44e7-a8d7-b851249b09e8)

**Comment by torikushiii** [comment]
sorry for the late reply,

did you check the console if there's any error printed out?

that could be mean only one thing that's the command folder is not being read correctly

**Comment by Malthinae** [comment]
Wasn't reading a file right, my error sorry, code works great thank you for the hard work!
