### ISSUE TITLE
[Suggestion] Multiple accounts?

### ISSUE THREAD

**Issue by DavidScann** [torikushiii/starrail-auto#2]
There used to be a Genshin Daily Check-in script that had the ability to work with several cookies, separated by commas. I wonder if you'll be able to add the same functionality to this script as well? Thank you for your work!

**Comment by torikushiii** [comment]
Thanks for the suggestion, I'll definitely take a look

**Comment by torikushiii** [comment]
Hello,

I've completed your request, you can see the instructions at the [README](https://github.com/torikushiii/starrail-auto#readme)

**Comment by DavidScann** [comment]
Fantastic! Thank you for including this feature. People with alts like me really do appreciate this
