### ISSUE TITLE
No cookie_token

### ISSUE THREAD

**Issue by Ningyoplug** [torikushiii/starrail-auto#21]
hello. i'm using Google Apps Script, as i only need the auto check in function, and I've noticed that the text says that the cookie should look like this in the end:
_MHYUUID=xxxx ; mi18nLang=en-us ; ltoken=xxxx ; ltuid=xxxx ; cookie_token=xxxx ; account_id=xxxx

however, there is no cookie_token anywhere in the result i get with document.cookie.
Here's what i get when i type document.cookie in the console (obviously i'm changing values into XXXX):

G_AUTHUSER_H=X; _MHYUUID=XXXX; DEVICEFP_SEED_ID=XXXX; DEVICEFP_SEED_TIME=XXXX; G_ENABLED_IDPS=google; mi18nLang=en-us; HYV_LOGIN_PLATFORM_OPTIONAL_AGREEMENT={XXXX:[]}; account_mid_v2=XXXX; account_id_v2=XXXX; ltmid_v2=XXXX; ltuid_v2=XXXX; DEVICEFP=XXXX; mi18nLang=en-us; HYV_LOGIN_PLATFORM_TRACKING_MAP={XXXX:{XXXX}}; HYV_LOGIN_PLATFORM_LIFECYCLE_ID={XXXX}

no cookie_token anywhere. so i have no idea what i have to put there exactly.

i'm using google chrome, latest version, but i've tried on firefox too and there's even less stuff there... i'm lost. it tells me [Error: Info API error: Not logged in] if i try to run it. nothing i've tried works. what am i supposed to do?
i'm a EU player btw, if it's useful.

i've also tried pasting the cookie exactly as it is and running but it still says the same thing. i am logged in on hoyoverse.

**Comment by torikushiii** [comment]
Hello,

there's another way to obtain cookie_token:
- First you'll need to open dev tools, go to network tab and go to check-in website (if you are at the website at the moment, refresh the site)
![image](https://github.com/torikushiii/starrail-auto/assets/21153445/7e3e4228-b44e-478e-b1b2-d9a82611efb7)

- Then you'll get a bunch of list of request name at this area, and at the filter box search for "home" and you'll get 1 result
![image](https://github.com/torikushiii/starrail-auto/assets/21153445/4aa79ba5-f5a7-471b-b3f8-41d4e85136de)

- And on Headers tab scroll down until you see cookie header
![image](https://github.com/torikushiii/starrail-auto/assets/21153445/ea7d503b-1806-4f17-8ffb-8f75bc225404)

**Comment by Ningyoplug** [comment]
Thank you! I was able to get all the information thanks to that method.

I copied and pasted the entire string that was in cookie into the value for COOKIE in Google Apps Script and it finally works now.

**Comment by sasukeuni** [comment]
Hi, it seems that mihoyo removed the _v2 from the cookie naiming making it fail to login
