### ISSUE TITLE
cant find ltuid to use as account_id

### ISSUE THREAD

**Issue by hazye06** [torikushiii/starrail-auto#22]
I used to be able to have ltuid in my cookie and my other friends also had it but mine doesnt.

![image](https://github.com/torikushiii/starrail-auto/assets/57023139/21b3faf4-dab2-434e-a556-86fd5cb95617)

I tried ltuid_v2 as well but it doesn't work, got any ideas?

**Comment by torikushiii** [comment]
I think it's related to the regex not catching the `account_id_v2` id, I've update the repo and tried with two different cookies and it should work fine now, whether you have `ltuid` or `ltuid_v2`

**Comment by hazye06** [comment]
It gives me an error still 

![image](https://github.com/torikushiii/starrail-auto/assets/57023139/98324f0b-803c-425e-84c7-a8adff82cbb6)
![image](https://github.com/torikushiii/starrail-auto/assets/57023139/0a5ab55f-3833-40ac-af77-8649d52154f0)

**Comment by torikushiii** [comment]
can you try a workaround on #21 and see if it's work fine

**Comment by hazye06** [comment]
the cookie from network is exactly the same as the image below

> ![image](https://user-images.githubusercontent.com/57023139/283757004-21b3faf4-dab2-434e-a556-86fd5cb95617.png)

the difference between the cookie from network and document.cookie from console is jus the ltoken_v2
also tried copypasting the cookie from network and still doesnt work

**Comment by hazye06** [comment]
hold on it worked after i added account_id(which i copied from ltuid_v2) into the cookie i got from network 
so i just needed ltoken_v2 to make it work for some reason

thanks for the help haha

**Comment by torikushiii** [comment]
glad the issue is resolved
