### ISSUE TITLE
node index.js error

### ISSUE THREAD

**Issue by calamitydeveloper** [torikushiii/starrail-auto#25]
![image](https://github.com/torikushiii/starrail-auto/assets/12202498/3eb792ea-ad0e-4cf9-929a-1138b7f0bc38)
what am i doing wrong here?

**Comment by torikushiii** [comment]
Thats mean the cookie you inserted are not valid, follow #21 instruction on how to obtain one and see if it's any help

**Comment by calamitydeveloper** [comment]
> Thats mean the cookie you inserted are not valid, follow #21 instruction on how to obtain one and see if it's any help

awesome, this fixed it thanks alot!
