### ISSUE TITLE
Codes Not Redeeming/ Daily Reminders not sending

### ISSUE THREAD

**Issue by Devorai** [torikushiii/starrail-auto#26]
Hello, I noticed that codes don't seem to be redeeming for me and reminders to do my dailies don't pop up. 

Everything else seems to be functional however (Stamina Threshold/Check In)/Expeditions Reminders)

 I have code redemption and check code set to true so i am unsure if  I have an issue or something else

Please advise thank you!

**Comment by torikushiii** [comment]
I've fixed the code not redeeming new one, and for the daily reminders I might have no idea because I've been testing it and it work just fine, it could've been the cron timer being entered wrong if you change the default timers

**Comment by Devorai** [comment]
Thanks for the swift update, I have already installed the new revision and am letting it run. Is there a timer as to when it will redeem /notify you for codes?

Also regarding daily/weekly reminders it was my own fault, i didnt see that it would not notify you if you had already completed it.

**Comment by torikushiii** [comment]
it should check new code every 30 minutes, there's no setting for it but you can change it at `crons/check-code-redeem`, it will redeem and notify you when there's new code instantly.

**Comment by Devorai** [comment]
Thank you got it work, I had to remove the newest code from the codes.js file for it to recognize I had not redeemed it yet (since it seems to download all codes into codes.js and classifies them as redeemed)

Maybe you could add an option to force  redeem all active codes or redeem codes the very first initial launch

Thanks for putting the effort into such a project it's very helpful!
