### ISSUE TITLE
Github Actions workflow integration

### ISSUE THREAD

**Issue by wijayaerick** [torikushiii/starrail-auto#28]
First of all, thank you for implementing this automation.
I've been running this for a few months with github action workflow setup.
- https://pastebin.com/1kZt1NFk

It'd be nice to have Github Actions integration; people will be able setup their automation by following steps:
1. Fork repo
2. Set secrets in the settings
3. Enable github action workflow

This will be applicable only with `--sign` flag because the workflow only runs short process.

I'm willing to work on this if it's ok for you.

**Comment by torikushiii** [comment]
Hi, thank you for your implementation suggestion and work.

But if I recall correctly, using GitHub actions as daily check-in is on gray area as I remember that it's violates against their Terms of Service but I do not remember what exactly.

**Comment by wijayaerick** [comment]
I'm not sure which ToS you're referring, but I assume it has something to do with the nature of this tool.
Thanks for the response, I think we can close this issue.

**Comment by torikushiii** [comment]
I will try to get some information in the meantime, If I'm wrong I'll reopen this suggestion again.
