### ISSUE TITLE
Not able to log in

### ISSUE THREAD

**Issue by baoanhng** [torikushiii/starrail-auto#29]
I followed all the steps and assumed there was nothing wrong with the process, but somehow I could not log in with the cookie.

```
message: 'API error when getting sign info',
  args: {
    statusCode: 200,
    body: { data: null, message: 'Not logged in', retcode: -100 }
  }
```

Do you have any idea of how this could go wrong? The cookie should be right, I even tried to logout and login again.

**Comment by torikushiii** [comment]
Please refer to #21 guide to see how to get the token, I forgot to update the guide properly.

**Comment by baoanhng** [comment]
> Please refer to #21 guide to see how to get the token, I forgot to update the guide properly.

Done, it is working right now, one notice that cookie_token is deprecated, it is now called ltoken_v2.

**Comment by baoanhng** [comment]
Devs are usually lazy, my suggestion is to let this issue open so people can look at it when they need to.

**Comment by torikushiii** [comment]
I've updated README instruction on how to get account cookie properly, I will close this issue now.

**Comment by baoanhng** [comment]
> I've updated README instruction on how to get account cookie properly, I will close this issue now.

I think you need to update README of getting cookie for Google Script page as well, or maybe just redirect it to main README instead.
