### ISSUE TITLE
[Error: Info API error: Not logged in]

### ISSUE THREAD

**Issue by burstdragon323** [torikushiii/starrail-auto#32]
I'm trying to get this to work but not having any success. I'm pretty much a noob when it comes to scripting so I bet I did something wrong.

**Comment by torikushiii** [comment]
You need to insert your cookie properly as written on readme or you can follow this #21 instructions to see if it's any help

**Comment by burstdragon323** [comment]
As far as I can tell I've entered the info properly and nothing in the #21 helped.

**Comment by torikushiii** [comment]
just to be sure, are you using it on Google Script or Node?

**Comment by burstdragon323** [comment]
Google Script

**Comment by torikushiii** [comment]
I've fixed the instruction properly on Google Script, it should be working fine now

**Comment by torikushiii** [comment]
If you still have some issue, you're welcome to ask on this issue again
