### ISSUE TITLE
Changing the value of Threshold in config has no response

### ISSUE THREAD

**Issue by Capoouo** [torikushiii/starrail-auto#35]
I changed the Threshold value in config.json to 200, but the screen display is 150
![螢幕擷取畫面 2024-01-08 180925](https://github.com/torikushiii/starrail-auto/assets/100028637/3e132fbc-2922-4d8a-b193-7c53403d61dd)

![螢幕擷取畫面 2024-01-08 181011](https://github.com/torikushiii/starrail-auto/assets/100028637/33a91170-da74-4d4e-8971-96f881ff824a)

**Comment by torikushiii** [comment]
I'm sorry, there was a typo there change `thershold` to `threshold`

**Comment by Capoouo** [comment]
> I'm sorry, there was a typo there change `thershold` to `threshold`

Working now very thanks<3
