### ISSUE TITLE
There is no config.js (other than under the classes directory) file only config.json. ReadMe is hard to grasp at first because of it

### ISSUE THREAD

**Issue by VacantTarnished** [torikushiii/starrail-auto#37]
So I ran into the Issue that I at first couldn't find the config.js because it either no longer exists or its a typo in the readme.  
I was also confused by this wording:
> Copy name and value (ltoken_v2 and ltuid_v2) and put it in your config.js file like this format name=value;
> - Remember to put "; (semicolon)" at every the end of value, e.g ltoken_v2=abc; ltuid_v2=123
  
Since it tells me (a developer maybe it's literally just a me being developer issue) to create 2 new variables in the config.js file so something like this:
```js
ltuid_v2 = 123;
ltoken_v2= "abc"
```

But since it is now under the config.json in the accounts object array in the cookie string I would change the wording to something like this:

> Copy name and value (`ltoken_v2` and `ltuid_v2`) and put it in your config.json file under the accounts list into the cookie with the format being `name=value`
> If done correctly it should look similar to this:
> - `cookie: "ltuid_v2=123;ltoken_v2=abc"`
> - Remember to put "; (semicolon)" at every the end of value, e.g ltoken_v2=abc; ltuid_v2=123

**Comment by VacantTarnished** [comment]
I just realised not only the readme need to be updated but the webhook and telegram file need to be updated aswell

Seems like I just found this project at a bad time where not everything in the readme's has been updated yet.

**Comment by torikushiii** [comment]
Yes, I was re-working the entire codebase and currently looking for bugs, but thank you for noticing the inconsistencies I will fix that soon!

~~For the `config.js` it was explained at Installation~~

**Comment by torikushiii** [comment]
Hello, I've updated the instructions properly on the `README` file, if there's still any unclear instruction, do tell me

**Comment by torikushiii** [comment]
If you're still have any question regarding this, feel free to comment on this issue.
