### ISSUE TITLE
API error when getting stamina info

### ISSUE THREAD

**Issue by the80hz** [torikushiii/starrail-auto#38]
I have a server on archlinux, on which the script runs without problems. When migrating config.json to another machine, for example, on wsl2 (ubuntu and arch) or Docker on another hardware, an API error occurs. Both computers have Node v21.6.2 installed.
Here's what the script writes when trying to get data on new computer with wsl2 archlinux: 
```
{
  message: 'API error when getting stamina info',
  args: {
    statusCode: 200,
    body: { data: null, message: 'invalid request', retcode: -10001 }
  }
}
```

![image](https://github.com/torikushiii/starrail-auto/assets/64586195/c5ea603e-f733-419b-97ae-4bedf47fb1e4)
![image](https://github.com/torikushiii/starrail-auto/assets/64586195/190b66f8-e823-4880-a2ab-aa18fca8a81a)

Here's what the script writes on the old computer without errors

![image](https://github.com/torikushiii/starrail-auto/assets/64586195/298c5491-c732-4499-9cd1-e1c730ade00b)
![image](https://github.com/torikushiii/starrail-auto/assets/64586195/189c68d3-1abc-4d95-854b-359a56099c22)

It would seem that the problem is with cookies, but my friend sent me a token that was made on a completely different hardware in a completely different place, and it works.

**Comment by torikushiii** [comment]
that specific error is a tricky one, since it can be anything such as:
	- DS salt is generated incorrectly (since it uses system time to generate the salt, see https://github.com/torikushiii/starrail-auto/blob/master/singletons/utils.js#L86 on how it generate the salt)
	- DS salt requires a new hash (which I doubt since I just tested it and it still working fine)
	- Request headers (such as user-agent, x-rpc-app_version or any x-rpc headers, which I still doubt because it still works fine when I tested it)
	- Their anti-bot system (usually fixed by logging-in first then running it again)

**Comment by torikushiii** [comment]
I will close this issue due to inactivity, if you have still any question regarding this feel free to comment here again
