### ISSUE TITLE
default.config.json/config.json discord_webhook not working/missing

### ISSUE THREAD

**Issue by Harrysdog** [torikushiii/starrail-auto#39]
![Image 400](https://github.com/torikushiii/starrail-auto/assets/135253560/1f88d29b-2bcb-4585-b13d-05388abde0cb)
where and how do i post discord webhook url into this? its not showing up in my channel

**Comment by Harrysdog** [comment]
also, guide only show how to get webhook url, not how or where to put the said url

**Comment by torikushiii** [comment]
the webhook url should be in here https://github.com/torikushiii/starrail-auto/blob/master/default.config.json#L46

> also, guide only show how to get webhook url, not how or where to put the said url

yeah, I totally forgot about that, thanks for the reminder!

**Comment by Harrysdog** [comment]
["DISCORD_WEBHOOK": null,]

do i replace null to https://discord.com/api/webhooks/xxxxxxx}
["DISCORD_WEBHOOK": https://discord.com/api/webhooks/xxxxxxx,]

or replace "DISCORD_WEBHOOK" to "https://discord.com/api/webhooks/xxxxxxx"
["https://discord.com/api/webhooks/xxxxxxx": null,]

or am i supposed to put it after null?
["DISCORD_WEBHOOK": null, https://discord.com/api/webhooks/xxxxxxx]

regardless, its not working even if null set to true

**Comment by torikushiii** [comment]
```
[
	"DISCORD_WEBOOK": "https://discord.com/api/webhooks/xxxxxxx"
]
```

**Comment by torikushiii** [comment]
hello, does that fixes the issue with your Discord webhook?

**Comment by Harrysdog** [comment]
webhook message not showing
also what error is this
![Image 401](https://github.com/torikushiii/starrail-auto/assets/135253560/111a6e47-35dd-4bb9-982f-bf248c5de08e)

**Comment by torikushiii** [comment]
that error means that one of your accounts have an invalid cookie, by that picture, it assume it's the first account since second account work just fine
