### ISSUE TITLE
Doubt regarding setting up environmental variables in Google Script 

### ISSUE THREAD

**Issue by ghost** [torikushiii/starrail-auto#4]
Hello,
I'm using the google script version of this script. I have a question. I heard that cookies data shouldn't be shared with anyone as anyone with my cookie can login into my hoyolab account.

How can we set up environmental variables in google script? Or there is nothing to worry about as my project in google script is private and no one can view my secret values. I have never used Google Script before that's why I am really confused.

Waiting for your response and thankyou.

**Comment by torikushiii** [comment]
Hi,

Yes that's true that you should not share your cookie with anyone.

But in google script at this part
![image](https://github.com/torikushiii/starrail-auto/assets/21153445/c2228586-f97d-47db-8c96-49b6bb20e7bb)

No one can see it but you, and your environmental variables are tied to your google account alone.

As for how to setup environmental variables at google script, I already wrote the guide on how to do this [here](https://github.com/torikushiii/starrail-auto/blob/master/services/google-script/README.md#setting-up), you can read from point 1 or immediately go to point 5 to see how to setup it.

If you still have any question, feel free to ask!

**Comment by ghost** [comment]
Hello,
Thanks for the prompt response. It solved my problem. 

Also I want to request another feature. The script notifies via discord. The thing is many people don't use discord. Is it possible for you to change the script so that we can get notified by Telegram.

Thanks

**Comment by torikushiii** [comment]
I've added the Telegram feature, please refer to this setup [guide](https://github.com/torikushiii/starrail-auto/blob/master/setup/TELEGRAM.md)

It's still on early implementation so please bear with the message formatting.

If you have any question, feel free to ask!
