### ISSUE TITLE
fresh install error,

### ISSUE THREAD

**Issue by Harrysdog** [torikushiii/starrail-auto#42]
i decided to do a fresh install as i sometime forgot to update but i found an error than new user may or may not get.
the only thing that change is the config.json (same as the old version)
![Image 482](https://github.com/torikushiii/starrail-auto/assets/135253560/93f2bb5b-6338-446b-9030-e38486c39eeb)

**Comment by torikushiii** [comment]
The error suggests that it's missing the chalk dependency. You'll need to run `npm install` and then try running the script again.

**Comment by Harrysdog** [comment]
not sure if this is only me but im gonna assume its related to to my custom check in or missing condition. this is the main reason why i did a fresh install
![Image 484](https://github.com/torikushiii/starrail-auto/assets/135253560/0733054a-a4aa-40c6-b3bc-51f802a48769)

**Comment by torikushiii** [comment]
it seems either request info is failed and this object have no data https://github.com/torikushiii/starrail-auto/blob/23dd6fc26efe9e94a6f02f1703e36a225e9c1b06/classes/check-in.js#L173-L178 or awards request returns an invalid data https://github.com/torikushiii/starrail-auto/blob/23dd6fc26efe9e94a6f02f1703e36a225e9c1b06/classes/check-in.js#L161 can you try printing out the response from both of those requests try writing
```js
console.log(info)
console.log(awards)
```

below this line https://github.com/torikushiii/starrail-auto/blob/23dd6fc26efe9e94a6f02f1703e36a225e9c1b06/classes/check-in.js#L160-L161

**Comment by Harrysdog** [comment]
the issue seems to resolve itself, nothing change. gonna keep this open in case it comes back

**Comment by Harrysdog** [comment]
this error seems to be a one time thing, its not major so im going to close this now
