### ISSUE TITLE
Auto redeem code doesn't work for the newest code

### ISSUE THREAD

**Issue by gwendolynemaxinegwenstacy** [torikushiii/starrail-auto#43]
Boothill banner dropped yesterday and we have a new code: FA2CU3P7P6QT
My scritp still running and it doesnt redeem new code, is there something changed? It was working fine for me in the last few month.

**Comment by torikushiii** [comment]
I noticed this yesterday and have been trying to figure out what was wrong with it. I believe they changed something in how redemption works.

I will try to look at it this week.

**Comment by torikushiii** [comment]
Hello, I've updated the code and it should working fine now, please pull/download the new version and follow the new [instruction](https://github.com/torikushiii/starrail-auto#usage)

If you still encounters any problem, feel free to ask.
