### ISSUE TITLE
running index.js 

### ISSUE THREAD

**Issue by Marziko** [torikushiii/starrail-auto#5]
So I tried to get this to run for a while and it just doesn't seem to really do anything? 
All I get when running node index.js is
PS C:\Users\Anwender\Documents\starrail-auto-master> node index.js
2023-06-08 23:33:44 [INFO]: Starting cronjobs...
2023-06-08 23:33:44 [INFO]: All cronjobs started successfully!

...and nothing else happens, I set up the config with my cookie and discord webhook url as well to see if the notifs were working

anything I'm missing here?

**Comment by torikushiii** [comment]
Hello,

When you're running "node index.js" only, it will only run the code on the scheduled time based from the CRON_TIMINGS at the config file, such as check-in only run at 00:00 midnight

If you run "node index.js --sign" then the code would run immediately

**Comment by Marziko** [comment]
> Hello,
> 
> When you're running "node index.js" only, it will only run the code on the scheduled time based from the CRON_TIMINGS at the config file, such as check-in only run at 00:00 midnight
> 
> If you run "node index.js --sign" then the code would run immediately

Makes sense, thank you.

Tried it with the command you provided, but I get an error thrown at me now:

Node.js v18.16.0
PS C:\Users\Anwender\Documents\starrail-auto-master> node index.js --sign
2023-06-09 16:38:32 [INFO]: Running check-in...
2023-06-09 16:38:33 [WARN]: [Account 1]: You've already checked in today, Trailblazer~
file:///C:/Users/Anwender/Documents/starrail-auto-master/lib/apps/check-in.js:56
                        throw new Error({
                              ^

CustomError: API error when getting sign info
- args: {"statusCode":200,"body":{"data":null,"message":"Not logged in","retcode":-100}}
    at CheckIn.getSignInfo (file:///C:/Users/Anwender/Documents/starrail-auto-master/lib/apps/check-in.js:56:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async CheckIn.checkAndSign (file:///C:/Users/Anwender/Documents/starrail-auto-master/lib/apps/check-in.js:141:35)
    at async file:///C:/Users/Anwender/Documents/starrail-auto-master/index.js:50:17 {
  [cause]: undefined
}

I think I'm missing something really obvious, I don't need to provide UID and cookie to both entries in the cfg, right?

**Comment by torikushiii** [comment]
That error indicates that your cookie is either invalid or expired.

As for UID and Cookie, you only need Cookie if you're only running with "--sign", so yes you're correct you don't need to run it with UID provided.

**Comment by Marziko** [comment]
So tried to run it again and tried the google scripts version too. Oddly enough the google scripts version works without a problem and my cookie works there, but can't get the node version to run whatsoever. Still getting the same error above

**Comment by torikushiii** [comment]
Hello, sorry for the late reply

If you're still interested in running it in node and not using google, I've reworked the entire codebase, give it a try and do tell me if there's still something wrong with it!

**Comment by Marziko** [comment]
Hello,

Tried the new version again and it works flawlessly now, thank you so much for your work!
