### ISSUE TITLE
Discord notification for stamina are not sending?

### ISSUE THREAD

**Issue by fenchai23** [torikushiii/starrail-auto#7]
I tested and it seems the daily claims are made at 12:00 am every day (a notification to my discord is sent via web-hooks)

but the stamina one does not seem to send anything>? I see the logs and the cron-job does trigger but I am unable to see any discord notification? even though I set the stamina threshold to a number lower than my current stamina:

example: 

```
Stamina for UID 6XXXXXXXX is above the threshold (137/180) - Capped in 4 hr, 16 min, 57 sec
```
the threshold does trigger but no notification is sent?

**Comment by torikushiii** [comment]
I just tested it with dummy data and sometimes it works and does not, which is weird.

I suspect that might be an unexpected behavior at the if statement at the `account.fired` code, I've tested and pushed new commit, let's see if it's fixed it.

If the issue still persist, please let me know.

**Comment by fenchai23** [comment]
so I did some testings...

On the first run, the notification gets sent properly 👍 

After the first run, any other notifications are not sent, is this intended? I guess not. There has to be some kind of issue with the Notification system.

**Comment by torikushiii** [comment]
Notifications only fire once and wait until your stamina is below threshold and set the `account.fired` to false, but I can change that since I see the use.

**Comment by fenchai23** [comment]
> Notifications only fire once and wait until your stamina is below threshold and set the `account.fired` to false, but I can change that since I see the use.

i see. Maybe an option in config.js to allow repeated notifications? sometimes a single notification might not be heard and is dismissed.

**Comment by torikushiii** [comment]
Hello, I've completed you're suggestion

Now you have an option to choose if you want to keep sending notification if  your stamina is above threshold or capped.
