### ISSUE TITLE
manual checks [--sign/stamina] were removed?

### ISSUE THREAD

**Issue by fenchai23** [torikushiii/starrail-auto#9]
is it possible to add them back? I prefer to check them manually to integrate with my other scripts.

**Comment by torikushiii** [comment]
Oh yeah, I totally forgot to reimplement those thing back

I'm sorry for the inconvenience.

I'll go work on it!

**Comment by torikushiii** [comment]
Hello,

I've added back the missing flags!

**Comment by fenchai23** [comment]
@torikushiii do you plan on adding the expedition flag as well? 

sorry, I am of no help, I only recently started coding commonjs, and you have refactored this so much that I am having issues of knowing what anything is doing 😅

**Comment by torikushiii** [comment]
Yes I will add it

But the current implementation is only checks if expedition is already done or not and does not return proper data like when does it ends.

**Comment by fenchai23** [comment]
> Yes I will add it
> 
> But the current implementation is only checks if expedition is already done or not and does not return proper data like when does it ends.

i see. It seems less useful than stamina and sign in then. thanks for the great job, anyway!

**Comment by torikushiii** [comment]
I've added `--expedition` flag and it will show like this if there's a current expedition is running

![image](https://github.com/torikushiii/starrail-auto/assets/21153445/f5268dde-e706-4603-94a0-fd60075e8d11)

**Comment by fenchai23** [comment]
nice, it even tells you the remaining time!

at this point, i think you got everything covered! the only thing I think you could add would be:

- auto (or manual) code redeeming.

I'm excited about what else you plan to implement 🙂.
